### ISSUE TITLE
Import Fails From WP - "Integrity constraint violation: 19 bolt_entries.slug may not be NULL"

### ISSUE THREAD

**Issue by brysont** [bolt/ImportWXR#14]
Hi Bob -

First, thanks for making this. Will be very helpful if I can get it to work. I'm importing from WP 4.5.2 into Bolt 2.2.19. I have posts mapping to entries, created the attachment content type, and have categories and tags set up for entries. The WP site I exported from include a lot of extra meta fields (post view and share counts, Visual Composer, etc.) that I'm not doing anything with on the import. Honestly just hoping those extra fields without a place in Bolt will just be ignored during import.

The dry run appears to complete successfully.

When I attempt to perform the import, I always get the same error: http://prntscr.com/b2v0qy

Before I start throwing config files at you, figured I'd best see what you need to see, if anything. I will add now that I'm mapping WP `post_name` to the slug field in Bolt for posts, attachments, and pages (though none exist in this test import). Grateful for any assistance you can provide. Just let me know what info you need from me.

Thanks.

**Comment by brysont** [comment]
My bad, forgot to include that I'm using SQLite on Bolt right now (this may change for a production site), and running PHP 5.6 on a Digital Ocean VPS; Debian 7. If any of that matters for this process, I don't think so, but there it is.

**Comment by brysont** [comment]
Also, just saw the release of Bolt v3 stable. I will maintain this v2.2 install for a bit, so I could still use help on this issue, but I will be setting up an additional install of v3 to check my theme's compatibility and new features. Will the importer be available for v3 anytime soon?

Thanks.

**Comment by bobdenotter** [comment]
We just tagged a new major version, that should have fixed this: https://github.com/bolt/ImportWXR/releases/tag/v2.0.0

If this remains a concern, feel free to re-open the issue.
